### ISSUE TITLE
[BUG] Generate without yml extension does not raise exception

### ISSUE THREAD

**Issue by hiepd** [theycallmemac/odin#41]
**Describe the bug**
Trying to generate job file using odin cli without yml extension just terminates without any error messages.

**To Reproduce**
```
./odin generate -f ./example -l go
```

**Expected behavior**
If extension is required, the command should return an error so users know what to expect.

**Comment by theycallmemac** [comment]
Yes, I believe there are a few commands which may exhibit this behaviour. Will take a look!
