### ISSUE TITLE
[DOCS] python is not a valid language identifier

### ISSUE THREAD

**Issue by ttymck** [theycallmemac/odin#45]
[The docs](https://github.com/theycallmemac/odin/blame/master/DOCS.md#L71) indicate `-l python` should be used, but [the source](https://github.com/theycallmemac/odin/blob/1bae27b9fcbe2e250c3f8dc99e89845ecb106cb6/odin-cli/pkg/commands/generate.go#L74) indicates the identifier is actually `python3`. I would be happy to update the docs, but I wanted to first ask if which identifier is desired/correct (or perhaps both?).

**Comment by theycallmemac** [comment]
@ttymck thanks for pointing this out,  I think both should be valid identifiers, the code should also be changed to reflect this.
